---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: ['markdown']
        stages: [commit]
      - id: trailing-whitespace
        exclude_types: ['markdown']
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
      - id: fix-byte-order-marker
        stages: [commit]
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-symlinks
        stages: [commit]
  - repo: https://github.com/zricethezav/gitleaks.git
    rev: v8.12.0
    hooks:
      - id: gitleaks
        stages: [commit]
