---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: ['markdown']
        stages: [commit]
      - id: trailing-whitespace
        exclude_types: ['markdown']
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
      - id: fix-byte-order-marker
        stages: [commit]
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-symlinks
        stages: [commit]
  - repo: https://github.com/zricethezav/gitleaks.git
    rev: v8.12.0
    hooks:
      - id: gitleaks
        stages: [commit]
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl

          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
