apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.pvc.accessModes | quote }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.pvc.reclaimPolicy | quote }}