{{- if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "safir.secretProviderClassName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  provider: azure
  parameters:
    usePodIdentity: {{ default "false" .Values.secretProviderClass.usePodIdentity | quote }}
    useVMManagedIdentity: {{ default "true" .Values.secretProviderClass.useVMManagedIdentity | quote }}
    userAssignedIdentityID: {{ default "" .Values.secretProviderClass.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.secretProviderClass.keyvaultName | quote }}
    cloudName: {{ default "AzurePublicCloud" .Values.secretProviderClass.cloudName | quote }}
    objects: |
      array:
      {{- include "common.tplvalues.render" (dict "value" .Values.secretProviderClass.objects "context" $) | nindent 6 }}
    tenantId: {{ .Values.secretProviderClass.tenantId | quote }}
  secretObjects:
    {{- if .Values.secretProviderClass.secretObjects }}
    {{- include "common.tplvalues.render" (dict "value" .Values.secretProviderClass.secretObjects "context" $) | nindent 4 }}
    {{- end }}
{{- end -}}
