{{- $jdbcString := .Values.safir.jdbcString }}
{{- $jdbcStringParts := split "://" $jdbcString }}
{{- $pgHost := (split ":" ($jdbcStringParts._1))._0 }}
{{- $pgPort := (split "/" (split ":" ($jdbcStringParts._1))._1)._0 }}
{{- $pgDatabase := (split "/" ($jdbcStringParts._1))._1 }}
{{- $safirDomain := .Values.safir.domain }}

{{- if .Values.cronjobs.safirUpdateStatistics.enabled -}}
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ printf "%s-safir-update-statistics" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.cronjobs.safirUpdateStatistics.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjobs.safirUpdateStatistics.historyLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels: {{- include "common.labels.standard" . | nindent 12 }}
          {{- if .Values.cronjobs.safirUpdateStatistics.podAnnotations }}
          annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.cronjobs.safirUpdateStatistics.podAnnotations "context" $) | nindent 12 }}
          {{- end }}
        spec:
          {{- if .Values.global.imagePullSecrets }}
          imagePullSecrets: {{- include "common.tplvalues.render" (dict "value" .Values.global.imagePullSecrets "context" $) | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          {{- if .Values.podSecurityContext.enabled }}
          securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          containers:
          - image: "{{ .Values.cronjobs.safirUpdateStatistics.image.repository }}:{{ .Values.cronjobs.safirUpdateStatistics.image.tag }}"
            imagePullPolicy: {{ .Values.cronjobs.safirUpdateStatistics.image.imagePullPolicy }}
            name: safir-update-statistics
            {{- if .Values.cronjobs.safirUpdateStatistics.command }}
            command:
{{ toYaml .Values.cronjobs.safirUpdateStatistics.command | indent 12 }}
            {{- end }}
            {{- with .Values.cronjobs.safirUpdateStatistics.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            env:
            - name: SAFIR_DOMAIN
              value: {{ $safirDomain | quote }}
            - name: PGHOST
              value: {{ $pgHost | quote }}
            - name: PGPORT
              value: {{ $pgPort | quote }}
            - name: PGDATABASE
              value: {{ $pgDatabase | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: safir-deployment-tomcat
                  key: SAFIR_DB_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: safir-deployment-tomcat
                  key: SAFIR_DB_PASSWORD
            {{- with .Values.cronjobs.safirUpdateStatistics.extraEnvVars }}
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with .Values.cronjobs.safirUpdateStatistics.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with .Values.cronjobs.safirUpdateStatistics.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with .Values.cronjobs.safirUpdateStatistics.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
{{- end }}
