global:
  imageRegistry: "ghcr.io"
  imagePullSecrets:
    - name: github-imagepullsecret
commonLabels:
  customer.gitops.natron.io/application: safir
  customer.gitops.natron.io/name: brf-solutions-test

safir:
  domain: safirtest.safirpro.com
  environment: prod
  jdbcString: "jdbc:postgresql://db-prod-safir.postgres.database.azure.com:5432/brf_solutions_test"

podLabels:
  customer.gitops.natron.io/application: safir
  customer.gitops.natron.io/name: brf-solutions-test

apache:
  image:
    repository: brf-solutions/safir-apache
    tag: 1.1.63
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "100m"
      memory: "200Mi"

tomcat:
  image:
    repository: brf-solutions/safir
    tag: 1.1.63
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1"
      memory: "2Gi"
  extraEnvVarsSecret: "safir-deployment-tomcat"

pvc:
  storage: "10Gi"
  storageClassName: "managed-premium"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: safirpro-staging
  hostname: safirtest.safirpro.com

secretProviderClass:
  enabled: true
  name: "azure-kv-prod-brf-solutions-safir-secrets"
  keyvaultName: kv-prod-brfsolutions
  tenantId: 3a46ee62-6dd0-4d46-a9b1-6fdc5426b6cb
  objects:
    - |
      objectName: github-imagepullsecret
      objectType: secret
      objectVersion: ""
    - |
      objectName: postgresql-brf-solutions-test-username
      objectType: secret
      objectVersion: ""
    - |
      objectName: postgresql-brf-solutions-test-password
      objectType: secret
      objectVersion: ""
  secretObjects:
    - secretName: github-imagepullsecret
      data:
      - key: .dockerconfigjson
        objectName: github-imagepullsecret
      type: kubernetes.io/dockerconfigjson
    - secretName: safir-deployment-tomcat
      data:
      - key: SAFIR_DB_USER
        objectName: postgresql-brf-solutions-test-username
      - key: SAFIR_DB_PASSWORD
        objectName: postgresql-brf-solutions-test-password
      type: Opaque