apiVersion: v2
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: A helm chart for shop application
home: https://github.com/natrongmbh/helm-charts
keywords:
  - shop
maintainers:
  - name: Natron Tech GmbH
    email: info@natron.io
  - name: BRF Solutions GmbH
    email: infrastructure@brf-solutions.ch
name: shop
version: 0.0.1
